config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :projects

    root to: "projects#index"
  end

  root 'pages#home'

  resources :projects, only: [:show] do
    resources :sprints, except: [:show]
    get 'dashboard' => 'sprints#dashboard'
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :sprints

  def last_sprint
    sprints.order(:number).last
  end
end

app/models/sprint.rb
class Sprint < ActiveRecord::Base
  belongs_to :project
  validates :number, presence: true
  validates :startDate, presence: true
  validates :endDate, presence: true
  validates :velocityForecast, presence: true
  validates :velocityReal, presence: true
  validates :internalBugs, presence: true
  validates :externalBugs, presence: true
  validates :teamSatisfaction, presence: true
  validates :clientSatisfaction, presence: true

  def next_sprint
    sprint = Sprint.new
    sprint.number = self.number + 1
    sprint.startDate = next_week_day(self.endDate)
    sprint.endDate = sprint.startDate + 13

    sprint
  end

  def next_week_day(date)
    ndate = date + 1
    if ndate.wday == 6 # saturday
      ndate += 1
    end
    if ndate.wday == 0 # sunday
      ndate += 1
    end
    ndate
  end

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Project.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Project.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/sprints_controller.rb
module Admin
  class SprintsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Sprint.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Sprint.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.order(:name)
    render :layout => 'login'
  end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_action :set_project
  before_action :set_sprint, only: [:edit, :update, :destroy]

  # GET /sprints
  def index
    @sprints = @project.sprints.order(:number)

    respond_to do |format|
      format.html
      format.json { render json: @sprints }
    end
  end

  # GET /sprints/new
  def new
    last_sprint = @project.last_sprint
    if last_sprint
      @sprint = last_sprint.next_sprint
    else
      @sprint = Sprint.new
      @sprint.startDate = DateTime.now.to_date
      @sprint.endDate = DateTime.now.to_date
    end
  end

  # GET /sprints/1/edit
  def edit
  end

  # POST /sprints
  def create
    @sprint = Sprint.new(sprint_params)
    @project.sprints << @sprint

    if @project.save
      redirect_to project_sprints_url, notice: 'Sprint was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sprints/1
  def update
    if @sprint.update(sprint_params)
      redirect_to project_sprints_url, notice: 'Sprint was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sprints/1
  def destroy
    @sprint.destroy
    redirect_to project_sprints_url, notice: 'Sprint was successfully destroyed.'
  end

  def dashboard
    @sprints = @project.sprints.order(:number)
    if !@sprints || @sprints.count == 0
      redirect_to project_sprints_url
    end

    @last_sprint = @sprints.last
    @bugs_data = @sprints.to_json(:only => [:number, :internalBugs, :externalBugs])
    @satisfaction_data = @sprints.to_json(:only => [:number, :teamSatisfaction, :clientSatisfaction])
    @velocity_data = @sprints.to_json(:only => [:endDate, :velocityForecast, :velocityReal])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprint
      @sprint = @project.sprints.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Only allow a trusted parameter "white list" through.
    def sprint_params
      params.require(:sprint).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_menu.html.erb
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">

    <div class="navbar nav_title" style="border: 0;">
      <a href="/" class="site_title">
        <i class="fa fa-tachometer"></i>
      </a>
    </div>
    <div class="clearfix"></div>


    <br/>

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

      <div class="menu_section">
        <ul class="nav side-menu">
          <li>
            <%= link_to project_dashboard_path do %>
              <i class="fa fa-bar-chart"></i>
              Dashboard
              <span class="fa fa-chevron-down"></span>
            <% end %>
          </li>
          <li>
            <%= link_to new_project_sprint_path do %>
              <i class="fa fa-edit"></i>
              Nouveau Sprint
              <span class="fa fa-chevron-down"></span>
              <% end %>
          </li>
          <li>
            <%= link_to project_sprints_path do %>
              <i class="fa fa-table"></i>
              Liste des Sprints
              <span class="fa fa-chevron-down"></span>
            <% end %>
          </li>
        </ul>
      </div>

    </div>
    <!-- /sidebar menu -->

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="ROBOTS" content="NOODP"/>
    <meta name="viewport" content="initial-scale=1"/>
    <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
    %>
    <title><%= title %></title>
    <%= stylesheet_link_tag :application, media: "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="nav-sm">
    <div class="container body">
      <div class="main_container">
        <%= render "menu" %>
        <div class="right_col" role="main">
          <%= yield %>
        </div>
        <%= render "javascript" %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="ROBOTS" content="NOODP"/>
    <meta name="viewport" content="initial-scale=1"/>
    <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
    %>
    <title><%= title %></title>
    <%= stylesheet_link_tag :application, media: "all" %>
    <%= csrf_meta_tags %>
  </head>

<body style="background:#F7F7F7;">

  <div class="">
    <a class="hiddenanchor" id="toregister"></a>
    <a class="hiddenanchor" id="tologin"></a>

    <div id="wrapper">
      <div id="login" class="animate form">
        <section class="login_content">
          <h1>Choisir un projet</h1>
          <ul class="list-unstyled">
            <% @projects.each do |project| %>
            <li>
              <a href='projects/<%=project.id%>/dashboard'
                class='btn btn-default' style="width:300px"><%=project.name%></a>
            </li>
            <% end %>
          </ul>
        <div class="clearfix"></div>
        <div class="separator">
          <!--
          <form>
            <h1>Login Form</h1>
            <div>
              <input type="text" class="form-control" placeholder="Username" required="" />
            </div>
            <div>
              <input type="password" class="form-control" placeholder="Password" required="" />
            </div>
            <div>
              <a class="btn btn-default submit" href="index.html">Log in</a>
              <a class="reset_pass" href="#">Lost your password?</a>
            </div>
            <div class="clearfix"></div>
            <div class="separator">
          -->
    <!-- form -->
        </section>
        <!-- content -->
      </div>
    </div>
  </div>

</body>

</html>

app/views/pages/home.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Plain Page</h3>
    </div>
  </div>
  <div class="clearfix"></div>
</div>

app/views/sprints/_form.html.erb
<%= simple_form_for [@project, @sprint], defaults: { wrapper_html: { class: 'col-md-6 col-sm-6 col-xs-12 form-group has-feedback' } } do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :number, wrapper_html: { class: 'col-md-12 col-sm-12 col-xs-12 form-group has-feedback'} %>
  <%= f.input :startDate, as: :string, input_html: { value: l(f.object.startDate) } %>
  <%= f.input :endDate, as: :string, input_html: { value: l(f.object.endDate) }  %>
  <%= f.input :velocityForecast, input_html: { autofocus:'autofocus'} %>
  <%= f.input :velocityReal %>
  <%= f.input :velocityComment, as: :text, wrapper_html: { class: 'col-md-12 col-sm-12 col-xs-12 form-group has-feedback'} %>
  <%= f.input :internalBugs %>
  <%= f.input :externalBugs %>
  <%= f.input :bugsComment, as: :text, wrapper_html: { class: 'col-md-12 col-sm-12 col-xs-12 form-group has-feedback'} %>
  <%= f.input :teamSatisfaction %>
  <%= f.input :clientSatisfaction %>
  <%= f.input :satisfactionComment, as: :text, wrapper_html: { class: 'col-md-12 col-sm-12 col-xs-12 form-group has-feedback'} %>
  <%= f.input :additionalNotes, as: :text, wrapper_html: { class: 'col-md-12 col-sm-12 col-xs-12 form-group has-feedback'} %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

<% content_for :javascript do %>
<script type="text/javascript">
  $(function () {
    $('#sprint_startDate').datetimepicker({
      locale: 'fr',
      format: 'L',
      daysOfWeekDisabled: [0, 6]
    });
    $('#sprint_endDate').datetimepicker({
      locale: 'fr',
      format: 'L',
      daysOfWeekDisabled: [0, 6]
    });
  });
</script>
<% end %>

app/views/sprints/dashboard.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= @project.name %>
        <br/> Dashboard Sprint
        <%= @last_sprint.number %></h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row tile_count">
    <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
      <div class="left"></div>
      <div class="right">
        <span class="count_top">
          <i class="fa fa-bolt"></i>
          Vélocité constatée
        </span>
        <div class="count"><%= @last_sprint.velocityReal %></div>
        <span class="sparkline_velocity" style="height: 160px;">
          <canvas style="display: inline-block; width: 196px; height: 40px; vertical-align: top;" width="196" height="40"></canvas>
        </span>
      </div>
    </div>
    <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
      <div class="left"></div>
      <div class="right">
        <span class="count_top">
          <i class="fa fa-bug"></i>
          Retours internes</span>
        <div class="count"><%= @last_sprint.internalBugs %></div>
        <span class="sparkline_internal" style="height: 160px;">
          <canvas style="display: inline-block; width: 196px; height: 40px; vertical-align: top;" width="196" height="40"></canvas>
        </span>
      </div>
    </div>
    <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
      <div class="left"></div>
      <div class="right">
        <span class="count_top">
          <i class="fa fa-bug"></i>
          Retours client</span>
        <div class="count"><%= @last_sprint.externalBugs %></div>
        <span class="sparkline_external" style="height: 160px;">
          <canvas style="display: inline-block; width: 196px; height: 40px; vertical-align: top;" width="196" height="40"></canvas>
        </span>
      </div>
    </div>
    <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
      <div class="left"></div>
      <div class="right">
        <span class="count_top">
          <i class="fa fa-smile-o"></i>
          Satisfaction équipe</span>
        <div class="count"><%= @last_sprint.teamSatisfaction %></div>
        <span class="sparkline_team" style="height: 160px;">
          <canvas style="display: inline-block; width: 196px; height: 40px; vertical-align: top;" width="196" height="40"></canvas>
        </span>
      </div>
    </div>
    <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
      <div class="left"></div>
      <div class="right">
        <span class="count_top">
          <i class="fa fa-smile-o"></i>
          Satisfaction client</span>
        <div class="count"><%= @last_sprint.clientSatisfaction %></div>
        <span class="sparkline_client" style="height: 160px;">
          <canvas style="display: inline-block; width: 196px; height: 40px; vertical-align: top;" width="196" height="40"></canvas>
        </span>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>

  <!-- fin header -->

  <div class="col-md-6 col-sm-6 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Vélocité
        </h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div id="graph_velocity" style="width:100%; height:280px;"></div>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-sm-6 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Commentaires
        </h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <pre style="width:100%; height:280px; margin-bottom:0; overflow:auto;"><%= @last_sprint.velocityComment %></pre>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="col-md-6 col-sm-6 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Retours
        </h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div id="graph_bugs" style="width:100%; height:280px;"></div>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-sm-6 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Commentaires
        </h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <pre style="width:100%; height:280px; margin-bottom:0; overflow:auto;"><%= @last_sprint.bugsComment %></pre>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="col-md-6 col-sm-6 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Satisfaction
        </h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div id="graph_satisfaction" style="width:100%; height:280px;"></div>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-sm-6 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Commentaires
        </h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <pre style="width:100%; height:280px; margin-bottom:0; overflow:auto;"><%= @last_sprint.satisfactionComment %></pre>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Notes générales
        </h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <pre style="width:100%; height:280px; margin-bottom:0; overflow:auto;"><%= @last_sprint.additionalNotes %></pre>
      </div>
    </div>
  </div>
    <div class="clearfix"></div>
</div>

<% content_for :javascript do %>
<script type="text/javascript">
  $('document').ready(function () {
    $(".sparkline_velocity").sparkline(<%= @sprints.map(&:velocityReal) %>, {
      type: 'line',
      height: '40',
      width: '80%',
      lineColor: '#26B99A',
      fillColor: 'rgba(223, 223, 223, 0.57)',
      lineWidth: 2,
      spotColor: '#26B99A',
      minSpotColor: '#26B99A',
      chartRangeMin: 0,
      chartRangeMinX: 0
    });

    $(".sparkline_internal").sparkline(<%= @sprints.map(&:internalBugs) %>, {
      type: 'bar',
      height: '40',
      barWidth: 9,
      barSpacing: 2,
      barColor: '#26B99A',
      chartRangeMin: 0,
      chartRangeMinX: 0
    });

    $(".sparkline_external").sparkline(<%= @sprints.map(&:externalBugs) %>, {
      type: 'bar',
      height: '40',
      barWidth: 9,
      barSpacing: 2,
      barColor: '#26B99A',
      chartRangeMin: 0,
      chartRangeMinX: 0
    });

    $(".sparkline_team").sparkline(<%= @sprints.map(&:teamSatisfaction) %>, {
      type: 'line',
      height: '40',
      width: '80%',
      lineColor: '#26B99A',
      fillColor: 'rgba(223, 223, 223, 0.57)',
      lineWidth: 2,
      spotColor: '#26B99A',
      minSpotColor: '#26B99A',
      chartRangeMin: 0,
      chartRangeMinX: 0
    });

    $(".sparkline_client").sparkline(<%= @sprints.map(&:clientSatisfaction) %>, {
      type: 'line',
      height: '40',
      width: '80%',
      lineColor: '#26B99A',
      fillColor: 'rgba(223, 223, 223, 0.57)',
      lineWidth: 2,
      spotColor: '#26B99A',
      minSpotColor: '#26B99A',
      chartRangeMin: 0,
      chartRangeMinX: 0
    });

    Morris.Bar({
      element: 'graph_bugs',
      data: <%= @bugs_data.html_safe %>,
      xkey: 'number',
      barColors: [
        '#26B99A', '#34495E', '#ACADAC', '#3498DB'
      ],
      ykeys: [
        'internalBugs', 'externalBugs'
      ],
      labels: [
        'Nb retours internes', 'Nb retours externes'
      ],
      hideHover: 'auto',
      xLabelAngle: 60
    });

    Morris.Bar({
      element: 'graph_satisfaction',
      data: <%= @satisfaction_data.html_safe %>,
      xkey: 'number',
      barColors: [
        '#26B99A', '#34495E', '#ACADAC', '#3498DB'
      ],
      ykeys: [
        'teamSatisfaction', 'clientSatisfaction'
      ],
      labels: [
        "Satisfaction de l'équipe", 'Satisfaction du client'
      ],
      hideHover: 'auto',
      xLabelAngle: 60
    });

    Morris.Line({
      element: 'graph_velocity',
      xkey: 'endDate',
      ykeys: [
        'velocityForecast', 'velocityReal'
      ],
      labels: [
        'Prévue', 'Constatée'
      ],
      hideHover: 'auto',
      smooth: 'false',
      lineColors: [
        '#ACADAC', '#34495E', '#ACADAC', '#3498DB'
      ],
      data: <%= @velocity_data.html_safe %>
    });
  });
</script>
<% end %>

app/views/sprints/edit.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= @project.name %></h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Editer sprint <%= @sprint.number %></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">

<%= render 'form' %>

</div></div></div></div></div>

app/views/sprints/index.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= @project.name %></h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Liste des sprints</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">

          <p id="notice"><%= notice %></p>

          <table class="table table-hover">
            <thead>
              <tr>
                <td>Numéro de sprint</td>
                <td>Date de début</td>
                <td>Date de fin</td>
                <td>Vélocité prévue</td>
                <td>Vélocité constatée</td>
                <td>Nombre de retours internes</td>
                <td>Nombre de retours externes</td>
                <td>Satisfaction de l'équipe</td>
                <td>Satisfaction du client</td>
                <th colspan="2"></th>
              </tr>
            </thead>

            <tbody>
              <% @sprints.each do |sprint| %>
              <tr>
                <td><%= sprint.number %></td>
                <td><%= l(sprint.startDate) %></td>
                <td><%= l(sprint.endDate) %></td>
                <td><%= sprint.velocityForecast %></td>
                <td><%= sprint.velocityReal %></td>
                <td><%= sprint.internalBugs %></td>
                <td><%= sprint.externalBugs %></td>
                <td><%= sprint.teamSatisfaction %></td>
                <td><%= sprint.clientSatisfaction %></td>
                <td><%= link_to 'Editer', [:edit, @project, sprint] %></td>
                <td><%= link_to 'Supprimer', [@project, sprint], method: :delete, data: { confirm: 'Sûr ?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sprints/new.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= @project.name %></h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Ajouter un sprint</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">

<%= render 'form' %>

</div></div></div></div></div>

app/views/sprints/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', [:edit, @project, @sprint] %> |
<%= link_to 'Back', project_sprints_path %>